Add variable for controlling pre-deploy command

diff --git a/bin/pre-deploy b/bin/pre-deploy
--- a/bin/pre-deploy
+++ b/bin/pre-deploy
@@ -1,8 +1,11 @@
 #!/usr/bin/env bash
 
-if [ ! -f application.jar ]; then
-    echo "Couldn't find application.jar"
-    exit 1
+if [[ -z $PRE_DEPLOY_COMMAND ]]; then
+    if [ ! -f application.jar ]; then
+        echo "Couldn't find application.jar"
+        exit 1
+    fi
+    PRE_DEPLOY_COMMAND="java $JAVA_OPTS -jar application.jar pre-deploy"
 fi
 
-java $JAVA_OPTS -jar application.jar pre-deploy
+$PRE_DEPLOY_COMMAND
